[package]
name = "datasets"
version = "0.1.0"
authors = ["Suyash <suyash93@protonmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.4"
flate2 = { version = "1.0.6", default-features = false, features = ["zlib"] }
indicatif = "0.11.0"
reqwest = "0.9.6"
tar = "0.4.20"
